apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: infra-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
    spec:
      containers:
      - name: controller
        image: k8s.gcr.io/ingress-nginx/controller:v1.4.0
        args:
        - /nginx-ingress-controller
        - --enable-ssl-passthrough
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
