apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: infra-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2023-03-20T20-16-18Z
        args:
        - server
        - /data
        env:
        - name: MINIO_ROOT_USER
          value: ayonminio
        - name: MINIO_ROOT_PASSWORD
          value: ayonminio123  # ⚠ Replace securely
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: infra-core
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
