apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: infra-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_DB
          value: ayon
        - name: POSTGRES_USER
          value: ayonuser
        - name: POSTGRES_PASSWORD
          value: ayonpass  # ⚠ Replace securely later!
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: infra-core
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
